using cse325_group_project.Components;
using cse325_group_project.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlite(builder.Configuration.GetConnectionString("DefaultConnection")));

// ---- Identity (auth) ----
// AddDefaultIdentity: user manager, sign-in manager, password hashing,
// plus the prebuilt UI pages at /Identity/Account/* (Register, Login, ...).
// AddRoles: enables the role system we need for Teacher/Student.
// AddEntityFrameworkStores: users and roles persist through our DbContext.
builder.Services.AddDefaultIdentity<ApplicationUser>(options =>
    {
        options.SignIn.RequireConfirmedAccount = false; // no email confirm step (no mail server in dev)
        options.Password.RequireNonAlphanumeric = false; // friendlier for class demo accounts
    })
    .AddRoles<IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>();

// Identity's pages are Razor Pages, so the app must serve those too.
builder.Services.AddRazorPages();

// Lets Blazor components receive the logged-in user via cascading state
// (what AuthorizeView and [Authorize] read from).
builder.Services.AddCascadingAuthenticationState();

var app = builder.Build();

// ---- Seed roles + a first teacher account on startup ----
using (var scope = app.Services.CreateScope())
{
    var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();
    foreach (var role in new[] { "Teacher", "Student" })
    {
        if (!await roleManager.RoleExistsAsync(role))
            await roleManager.CreateAsync(new IdentityRole(role));
    }

    var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
    var teacherEmail = "teacher@institute.test";
    if (await userManager.FindByEmailAsync(teacherEmail) is null)
    {
        var teacher = new ApplicationUser { UserName = teacherEmail, Email = teacherEmail, EmailConfirmed = true };
        await userManager.CreateAsync(teacher, "Teacher123$");
        await userManager.AddToRoleAsync(teacher, "Teacher");
    }
}

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseAntiforgery();

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

// Serves the Identity UI pages (/Identity/Account/Login etc.)
app.MapRazorPages();

// Files are stored outside wwwroot and can only be downloaded after an authorization check.
app.MapGet("/materials/download/{id:int}", async Task<IResult> (int id, HttpContext http, ApplicationDbContext db, IWebHostEnvironment environment) =>
{
    if (http.User.Identity?.IsAuthenticated != true)
        return Results.Challenge();

    var userId = http.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
    if (string.IsNullOrWhiteSpace(userId))
        return Results.Forbid();

    var material = await db.Materials.SingleOrDefaultAsync(m => m.Id == id);
    if (material is null)
        return Results.NotFound();
    var course = await db.Courses.SingleOrDefaultAsync(c => c.Id == material.CourseId);
    if (course is null)
        return Results.NotFound();

    var isTeacher = http.User.IsInRole("Teacher");
    var isStudent = http.User.IsInRole("Student");
    var allowed = isTeacher
        ? material.UploadedByTeacherId == userId && course.TeacherId == userId
        : isStudent && await db.Enrollments.AnyAsync(e => e.StudentId == userId && e.CourseId == material.CourseId);

    if (!allowed)
        return Results.Forbid();

    // StorageId is generated by the server. Reject path separators even if database data is altered.
    if (string.IsNullOrWhiteSpace(material.StorageId) || material.StorageId != Path.GetFileName(material.StorageId))
        return Results.NotFound();

    var filePath = Path.Combine(environment.ContentRootPath, "App_Data", "class-materials", material.StorageId);
    if (!File.Exists(filePath))
        return Results.NotFound();

    var contentType = Path.GetExtension(material.FileName).ToLowerInvariant() switch
    {
        ".pdf" => "application/pdf",
        ".ppt" => "application/vnd.ms-powerpoint",
        ".pptx" => "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        ".doc" => "application/msword",
        ".docx" => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ".txt" => "text/plain",
        _ => "application/octet-stream"
    };

    return Results.File(filePath, contentType, Path.GetFileName(material.FileName), enableRangeProcessing: true);
}).RequireAuthorization();

app.Run();
